Controllers/SingularController.cs
using CommercialApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace CommercialApp.Controllers
{
    public class SingularController : Controller
    {

        #region Contructor
        private readonly CAppDbContext _context;
        private IHttpContextAccessor acessor { get; set; }
        public SingularController(CAppDbContext context, IHttpContextAccessor a)
        {
            _context = context;
            acessor = a;
        }
        #endregion

        //Acessing the list of all Singular users is only acessible for the user "admin"
        #region Index
        // GET: Singular
        public async Task<IActionResult> Index()
        {
            if (acessor.HttpContext.Session.GetString("user") == "admin")
            {
                var cAppDbContext = await _context.Singular.ToListAsync();
                return View(cAppDbContext);
            }
            return RedirectToAction("Index", "Home");

        }
        #endregion

        //Acessing the detailed information of any Singular user is only available for the user "admin"
        #region Details
        // GET: Singular/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (acessor.HttpContext.Session.GetString("user") == "admin")
            {

                var singular = await _context.Singular
                .FirstOrDefaultAsync(m => m.PeopleId == id);
                if (singular == null)
                {
                    return NotFound();
                }

                return View(singular);
            }
            return RedirectToAction("Index", "Home");

        }
        #endregion

        //Creating a new Singular user is only available is there is no user logged (Register) or for the user "admin"
        #region Create
        // GET: Singular/Create
        public IActionResult Create()
        {
            if (acessor.HttpContext.Session.GetString("user") == null || acessor.HttpContext.Session.GetString("user") == "admin")
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        // POST: Singular/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Singular singular)
        {
            if (ModelState.IsValid)
            {

                _context.Add(singular);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(singular);
        }
        #endregion

        //Editing information of the user is only available for the user itself or for the user "admin"
        #region Edit
        // GET: Singular/Edit/5
        public async Task<IActionResult> Edit(int id)
        {


            var singular = await _context.Singular.FindAsync(id);
            if (singular == null)
            {
                return NotFound();
            }
            if (acessor.HttpContext.Session.GetString("user") == singular.Name || acessor.HttpContext.Session.GetString("user") == "admin")
            {
                return View(singular);
            }
            return RedirectToAction("Index", "Home");

        }

        // POST: Singular/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Singular singular)
        {


            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(singular);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SingularExists(singular.PeopleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(singular);
        }
        #endregion

        //Only the user "admin" can delete users
        #region Delete
        // GET: Singular/Delete/5
        public async Task<IActionResult> Delete(int id)
        {

            if (acessor.HttpContext.Session.GetString("user") == "admin")
            {
                var singular = await _context.Singular
                .FirstOrDefaultAsync(m => m.PeopleId == id);
                if (singular == null)
                {
                    return NotFound();
                }

                return View(singular);
            }
            return RedirectToAction("Index", "Home");

        }

        // POST: Singular/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var singular = await _context.Singular.FindAsync(id);
            _context.Remove(singular);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region SingularExists
        private bool SingularExists(int id)
        {
            return _context.Singular.Any(e => e.PeopleId == id);
        }
        #endregion

    }
}

Controllers/TransactionController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using CommercialApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CommercialApp.Controllers
{
    public class TransactionController : Controller
    {

        #region Constructor
        private readonly CAppDbContext _context;

        private readonly INotyfService _notyf;
        private IHttpContextAccessor acessor { get; set; }

        public TransactionController(CAppDbContext context, IHttpContextAccessor a, INotyfService notyf)
        {
            _context = context;
            acessor = a;
            _notyf = notyf;
        }
        #endregion

        //Three diferent actions to acess lists of transactions:
        //Index - wich is only available for the user "admin"
        //GetTransactionByCompany wich is only available for Companies
        //GetTransactionByCompany wich is only available for Singular users
        #region Index
        // GET: Transaction
        public async Task<IActionResult> Index()
        {
            if (acessor.HttpContext.Session.GetString("user") == "admin")
            {
                var cAppDbContext = await _context.Transaction.Include(t => t.Singular).ToListAsync();
                return View(cAppDbContext);
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> GetTransactionByCompany()
        {
            if (acessor.HttpContext.Session.GetString("type") == "company")
            {
                int idx = Convert.ToInt32(acessor.HttpContext.Session.GetString("userId"));
                IEnumerable<Transaction> cAppDbContext = await _context.Transaction.Include(t => t.Singular).Include(t => t.TransactionDetails).ThenInclude(t => t.Product).ThenInclude(t => t.Company).ToListAsync();
                IEnumerable<TransactionDetail> tds = await _context.TransactionDetail.Include(t => t.Product).ToListAsync();
                List<Transaction> tByCompany = new List<Transaction>();


                foreach (TransactionDetail item in tds)
                {
                    if (item.Product.CompanyId == idx)
                    {
                        Transaction t = await _context.Transaction.Where(t => t.TransactionId == item.TransactionId).Include(t => t.TransactionDetails).ThenInclude(t => t.Product).ThenInclude(t => t.Company).FirstOrDefaultAsync();

                        tByCompany.Add(t);
                    }
                }

                return View(tByCompany);
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> GetTransactionByUser(int id)
        {
            if (acessor.HttpContext.Session.GetString("type") == "singular")
            {
                List<Transaction> transactions = await _context.Transaction.Where(m => m.Singular.PeopleId == id).Include(m => m.TransactionDetails).ToListAsync();


                if (transactions.Count == 0)
                {
                    ViewBag.Error = "You have no orders registered";
                }

                return View(transactions);
            }
            return RedirectToAction("Index", "Home");
        }
        #endregion

        //Three diferent actions to acess details of transactions:
        //Details - wich is only available for the user "admin"
        //DetailsCompany wich is only available for Companies
        //DetailsSingular wich is only available for Singular users
        #region Details
        // GET: Transaction/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var transaction = await _context.Transaction.Include(t => t.Singular).Include(t => t.TransactionDetails).ThenInclude(t => t.Product).FirstOrDefaultAsync(m => m.TransactionId == id);

            if (transaction == null)
            {
                return NotFound();
            }

            if (acessor.HttpContext.Session.GetString("user") == "admin")
            {
                return View(transaction);
            }
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> DetailsSingular(int id)
        {
            if (acessor.HttpContext.Session.GetString("type") == "singular")
            {
                var transaction = await _context.Transaction.Include(t => t.Singular).Include(t => t.TransactionDetails).ThenInclude(t => t.Product).ThenInclude(t => t.Company).FirstOrDefaultAsync(m => m.TransactionId == id);

                return View(transaction);
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> DetailsCompany(int id)
        {
            if (acessor.HttpContext.Session.GetString("type") == "company")
            {
                var transaction = await _context.Transaction.Include(t => t.Singular).Include(t => t.TransactionDetails).ThenInclude(t => t.Product).ThenInclude(t => t.Company).FirstOrDefaultAsync(m => m.TransactionId == id);

                return View(transaction);
            }
            return RedirectToAction("Index", "Home");
        }
        #endregion

        //These actions will be used to manage the Transactions/ShoppingCart and are only acessible for Singular users
        #region Cart

        public async Task<IActionResult> AddToCart(int id)
        {
            if (acessor.HttpContext.Session.GetString("type") == "singular")
            {
                int idx = Convert.ToInt32(acessor.HttpContext.Session.GetString("userId"));

                Transaction transaction = await _context.Transaction.Where(u => u.SingularId.Equals(idx) && u.State == "Open").FirstOrDefaultAsync();
                Singular singular = await _context.Singular.Where(u => u.PeopleId.Equals(idx)).FirstOrDefaultAsync();

                if (transaction == null)
                {


                    Transaction newTransaction = new Transaction();
                    newTransaction.State = "Open";
                    newTransaction.DateCreated = DateTime.Now;
                    newTransaction.ChangedBy = acessor.HttpContext.Session.GetString("user");
                    newTransaction.SingularId = Convert.ToInt32(acessor.HttpContext.Session.GetString("userId"));
                    _context.Transaction.Add(newTransaction);
                    await _context.SaveChangesAsync();

                    TransactionDetail tdtl = new TransactionDetail();
                    tdtl.ProductId = id;
                    tdtl.Quantity = 1;
                    tdtl.TransactionId = newTransaction.TransactionId;

                    Product pdt = await _context.Product.FirstOrDefaultAsync(m => m.ProductId == tdtl.ProductId);
                    tdtl.Product = pdt;
                    tdtl.UnitPrice = pdt.UnitPrice;


                    _context.TransactionDetail.Add(tdtl);
                    await _context.SaveChangesAsync();
                    newTransaction.Total += tdtl.Product.GetPriceWithTax();
                    await _context.SaveChangesAsync();
                    _notyf.Custom("Item added to the cart", 10, "#E3B1B1", "fa fa-shopping-cart"); string tsId = Convert.ToString(tdtl.TransactionId);
                    this.HttpContext.Session.SetString("transactionId", tsId);


                    if (acessor.HttpContext.Session.GetString("cartCount") != "" && acessor.HttpContext.Session.GetString("cartCount") != "!")
                    {
                        int cart = Convert.ToInt32(acessor.HttpContext.Session.GetString("cartCount"));
                        int cartCountInt = cart + 1;
                        string cartCount = Convert.ToString(cartCountInt);
                        this.HttpContext.Session.SetString("cartCount", cartCount);
                    }
                    else
                        this.HttpContext.Session.SetString("cartCount", "1");


                    return RedirectToAction("Index", "Product");
                }


                if (acessor.HttpContext.Session.GetString("cartCount") != "" && acessor.HttpContext.Session.GetString("cartCount") != "!")
                {
                    int cart = Convert.ToInt32(acessor.HttpContext.Session.GetString("cartCount"));
                    int cartCountInt = cart + 1;
                    string cartCount = Convert.ToString(cartCountInt);
                    this.HttpContext.Session.SetString("cartCount", cartCount);
                }
                else
                    this.HttpContext.Session.SetString("cartCount", "1");

                TransactionDetail tdt = new TransactionDetail();
                tdt.ProductId = id;
                tdt.Quantity = 1;
                tdt.TransactionId = transaction.TransactionId;

                Product pd = await _context.Product.FirstOrDefaultAsync(m => m.ProductId == tdt.ProductId);
                tdt.Product = pd;
                tdt.UnitPrice = pd.UnitPrice;


                _context.TransactionDetail.Add(tdt);
                await _context.SaveChangesAsync();
                transaction.Total += tdt.Product.GetPriceWithTax();
                await _context.SaveChangesAsync();
                _notyf.Custom("Item added to the cart", 10, "#E3B1B1", "fa fa-shopping-cart"); string tId = Convert.ToString(tdt.TransactionId);
                this.HttpContext.Session.SetString("transactionId", tId);

                return RedirectToAction("Index", "Product");
            }
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> RemoveProduct(int id)
        {
            if (acessor.HttpContext.Session.GetString("type") == "singular")
            {

Views/Transaction/Create.cshtml
@model CommercialApp.Models.Transaction

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Transaction</h4>
<hr />
<div class="row">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SingularId" class="control-label"></label>
                <select asp-for="SingularId" class="form-control" asp-items="ViewBag.SingularId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChangedBy" class="control-label"></label>
                <input asp-for="ChangedBy" class="form-control" />
                <span asp-validation-for="ChangedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Transaction/Delete.cshtml
@model CommercialApp.Models.Transaction

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Singular)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Singular.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ChangedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChangedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="TransactionId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Transaction/Details.cshtml
@model CommercialApp.Models.Transaction


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

    <div>
        <h4>Transaction</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TransactionId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TransactionId)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DateCreated)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DateCreated)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.State)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.State)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ChangedBy)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ChangedBy)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Total)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Total)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Singular)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Singular.Name)
            </dd>
            <dt class="col-sm-2">
                Address
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Singular.Address) -  @Html.DisplayFor(model => model.Singular.PostalCode) -  @Html.DisplayFor(model => model.Singular.City)
            </dd>
            @foreach (CommercialApp.Models.TransactionDetail x in Model.TransactionDetails)
            {
                <dt class="col-sm-2">
                    Product
                </dt>
                <dd class="col-sm-10">
                    @x.Product.Name
                </dd>
                <dt class="col-sm-2">
                    Price Without Taxes
                </dt>
                <dd class="col-sm-10">
                    @x.Product.UnitPrice
                </dd>
                <dt class="col-sm-2">
                    Taxe Rate
                </dt>
                <dd class="col-sm-10">
                    @x.Product.TaxRate
                </dd>
                <dt class="col-sm-2">
                    Price With Taxes
                </dt>
                <dd class="col-sm-10">
                    @x.Product.GetPriceWithTax()
                </dd>



            }
        </dl>
    </div>

    <div>
        <a asp-action="Edit" asp-route-id="@Model.TransactionId">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
</body>
</html>

Views/Transaction/DetailsSingular.cshtml
@model CommercialApp.Models.Transaction

@{
    ViewData["Title"] = "DetailsSingular";
}

<br />
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <br><br>
        <h4 class="text-center">Shopping cart</h4>
        <br><br>
        <div class="container">
            <table class="table">
                <h5 class="text-center">Products</h5>
                <br>
                <thead>
                    <tr>
                        <th>
                            Product
                        </th>
                        <th>
                            Supplied By
                        </th>
                        <th>
                            Image
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Unit Price (without taxes)
                        </th>
                        <th>
                            Tax Rate %
                        </th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.TransactionDetails.Count() == 0)
                    {
                        <p>There are no products in your cart yet</p>
                    }
                    @foreach (CommercialApp.Models.TransactionDetail x in Model.TransactionDetails)
                    {

                        <tr>
                            <td>
                                @(x.Product.Name)
                            </td>
                            <td>
                                @(x.Product.Company.Name)
                            </td>
                            <td>
                                <img src="data:image;base64,@System.Convert.ToBase64String(x.Product.Image)" width="80" height="80" />
                            </td>
                            <td>
                                @(x.Product.Description)
                            </td>
                            <td>
                                @(x.Product.UnitPrice)
                            </td>
                            <td>
                                @(x.Product.TaxRate)
                            </td>
                            @if (Model.State == "Open")
                            {
                                <td>
                                    @Html.ActionLink("-", "RemoveProduct", "Transaction", new { id = x.TransactionDetailId })
                                </td>
                                <td>
                                    @Html.ActionLink("+", "AddAnotherProduct", "Transaction", new { id = x.ProductId })
                                </td>
                            }
                        </tr>

                    }
                </tbody>
            </table>


            <p>Quantity: @Model.TransactionDetails.Count()</p>
            <p>Total (with taxes): @Html.DisplayFor(model => model.Total)</p>
            <br><br>
            <h5 class="text-center">Delivery information</h5>
            <br>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Name
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Singular.Email)
                        </th>
                        <th>
                            Contact Number
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Singular.Address)
                        </th>
                        <th>
                            Postal code
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Singular.City)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            @Html.DisplayFor(model => model.Singular.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Singular.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Singular.PhoneNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Singular.Address)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Singular.PostalCode)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Singular.City)
                        </td>
                        @if (Model.State == "Open")
                        {
                            <td>
                                @Html.ActionLink("Edit", "Edit", "Singular", new { id = Model.Singular.PeopleId })
                            </td>
                        }
                    </tr>
                </tbody>
            </table>
            <br>
            <div class="form-group">
                @if (Model.State == "Open")
                {
                    <p class="btn btn-primary">@Html.ActionLink("Confirm", "ChangeState", "Transaction", new { id = Model.TransactionId })</p>
                    <p class="btn btn-primary">@Html.ActionLink("Delete this cart", "Delete", "Transaction", new { id = Model.TransactionId })</p>
                }
                @if (Model.State == "Awaiting treatment")
                {
                    <p class="btn btn-primary" > @Html.ActionLink("Confirm Reception", "ConfirmReception", new { id = Model.TransactionId })</p>
                }
            </div>
        </div>
    </div>
</body>
</html>

Views/Transaction/Edit.cshtml
@model CommercialApp.Models.Transaction

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Transaction</h4>
<hr />
<div class="row">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="TransactionId" />
        <input type="hidden" asp-for="SingularId" />
        
        <div class="form-group">
            <label asp-for="DateCreated" class="control-label"></label>
            <input asp-for="DateCreated" class="form-control" />
            <span asp-validation-for="DateCreated" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="State" class="control-label"></label>
            <input asp-for="State" class="form-control" />
            <span asp-validation-for="State" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ChangedBy" class="control-label"></label>
            <input asp-for="ChangedBy" class="form-control" />
            <span asp-validation-for="ChangedBy" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Total" class="control-label"></label>
            <input asp-for="Total" class="form-control" />
            <span asp-validation-for="Total" class="text-danger"></span>
        </div>        
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </form>
    </div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Transaction/GetTransactionByCompany.cshtml
@model IEnumerable<CommercialApp.Models.Transaction>

@{
    ViewData["Title"] = "Index";
}
<br />

<h1>Orders that have products I supply</h1>
<br />
<div class="text-danger">
    @ViewBag.Error
</div>
@if (Model.Count() == 0)
{
    <p>There are still no sellings registered</p>
}
@foreach (CommercialApp.Models.Transaction item in Model)
{

    <table class="table">
        <thead>
            <tr>
                <th>
                    Date
                </th>
                <th>
                    State
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @item.DateCreated
                </td>
                <td>
                    @item.State
                </td>
                <td>
                    @Html.ActionLink("Details", "DetailsCompany", new { id = item.TransactionId })
                </td>
            </tr>

        </tbody>
    </table>

}